apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ms-smsbank-3ds-deploy
  labels:
    app: ms-smsbank-3ds
    component: ms-smsbank-3ds-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-smsbank-3ds
        component: ms-smsbank-3ds
        enabled: "true"
    spec:
      imagePullSecrets:
        - name: regcred
      hostAliases:
        - ip: "192.168.110.130"
          hostnames:
            - "ufctest.pshb.local"
        - ip: "192.168.109.129"
          hostnames:
            - "fcjuat"
      containers:
        - name: ms-smsbank-3ds
          image: 192.168.10.253:18443/repository/analoglab/ms-smsbank-3ds:latest
          securityContext:
            privileged: true
          imagePullPolicy: Always
          ports:
            - name: ms-smsbank-3ds
              containerPort: 8019